### ISSUE TITLE
Comment about pytest-reportlog

### ISSUE THREAD

**Issue by nicoddemus** [asottile/detect-test-pollution#2]
Was browsing the code and came across this comment:

https://github.com/asottile/detect-test-pollution/blob/cb049b119f6f6e17287e6cdbf3544c5632b6fd78/detect_test_pollution.py#L15

Wanted to point out that https://github.com/pytest-dev/pytest-reportlog is meant to support this use case exactly. If any feature you need is missing, should be easy to enhance that plugin too.

**Comment by asottile** [comment]
heh yeah -- I'd rather not depend on another plugin though -- too many moving parts already!

thanks though!
