### ISSUE TITLE
Detecting Flaky Test Pollution

### ISSUE THREAD

**Issue by mimre25** [asottile/detect-test-pollution#78]
The title says it. 

I have a test suite that runs into a flaky test pollution. 
While reworking the test set is one option, I was wondering if you have encountered such a case and if so, do you have a strategy to detect it with this tool?

**Comment by asottile** [comment]
what do you mean?

**Comment by asottile** [comment]
if it's flaky that's not a pollution

**Comment by mimre25** [comment]
Maybe my example was unclear or we have a misunderstanding:

Let's say I have test `T`, which on its own passes 100% of the time. So that's definitely not flaky. 
Now, when I run `T` within a test suite, it fails every now and then due to some sort of test pollution.

Would you still call `T` flaky in such a scenario? 

Either way, have you ever encountered such a situation and used `detect-test-pollution` to find the test that leaks to `T` failing on occasion?
