### ISSUE TITLE
handling multiple test directories?

### ISSUE THREAD

**Issue by chrishavlin** [asottile/detect-test-pollution#85]
Hi there! thanks for the plugin, very helpful!

Just wondering: is there any way to handle the case where you have tests stored in different directories? I'm trying to identify the origins of some test pollution with a layout that looks like:

```
packagename
├── __init__.py
├── module1
│   ├── __init__.py
│   ├── module1.py
│   ├── tests
│   │   ├── __init__.py
│   │   ├── test_a.py
│   │   ├── test_b.py
├── module2
│   ├── __init__.py
│   ├── module2.py
│   ├── tests
│   │   ├── __init__.py
│   │   ├── test_c.py
│   │   ├── test_d.py
```

I can reproduce the failure when running with just pytest with just 

```
pytest packagename/module1/tests/ packagename/module2/tests/test_d.py::failing_test_id
```

but to use `detect-test-pollution` the following would result in a " failing test was not part of discovered tests!" error:

```
detect-test-pollution  --failing-test packagename/module2/tests/test_d.py::failing_test_id  --tests packagename/module1/tests/
```

while I could use 

```
detect-test-pollution --failing-test packagename/module2/tests/test_d.py::failing_test_id  --tests packagename/
```

I wanted to take advantage of the manual bisecting that I had already done. I ended up just copying over `test_d.py` over to `packagename/module1/tests/`, but it'd be nice if I could avoid that (i.e., if `--tests` could accept multiple paths).

**Comment by asottile** [comment]
you can use their common package root

but I would suggest using a standard layout. I'm not going to add support for this
